# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

def myanswer(n: int):
    print("\n" + "="*64)
    answer(n)

def myhint(n: int):
    print("\n" + "="*64)
    hint(n) 

# myhint(1)

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
np.show_config()
# help(np)

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
Supported SIMD extensions in this Num

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
# np.size(x)
Z = np.zeros((10, 4))
print(np.size(Z))
print(Z.itemsize)
print(f"{np.size(Z)=}, {Z.itemsize=}, {Z.size*Z.itemsize=}")
print(f"{Z.nbytes=}")

# myanswer(4)

40
8
np.size(Z)=40, Z.itemsize=8, Z.size*Z.itemsize=320
Z.nbytes=320


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
# help(np)
# np.info(np.add)
!python -c "import numpy as np; np.info(np.add)"
# myanswer(5)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [93]:
X = np.zeros(10)
X[4] = 1
print(X)
# myanswer(6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [106]:
X = np.array([ i for i in range(10, 50) ])
print(X, "\n")
Z = np.arange(10, 50)

print(Z == X)
myanswer(7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [131]:
# help(X)
X = np.arange(10, 50)
print(X)
X = X[::-1]
print(X)
Z = X[::-2]
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [130]:
X = np.arange(0, 9).reshape((3,3))
print(X)
myanswer(9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [145]:
X = np.array([1,2,0,0,4,0])
nzX = np.nonzero(X)
# XPred = X != 0
print(nzX)
# np.info(np.nonzero)

Z = X.reshape(2,3)
print(Z)
nzIdx = np.nonzero(Z)
print(nz)
print(Z[nzIdx])
# myanswer(10)

(array([0, 1, 4]),)
[[1 2 0]
 [0 4 0]]
(array([0, 0, 1]), array([0, 1, 1]))
[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [8]:
# np.info(np.eye)
X = np.eye(3)
print(X)
# myanswer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
# np.info(np.random)
X = np.random.random((3,3,3))
print(X)
Z = X.reshape(-1)

print(Z)
predZ = Z >= 0.5
print(Z[np.nonzero(predZ)].size)
# myanswer(12)

[[[0.27286602 0.7565374  0.03819818]
  [0.34440667 0.03709606 0.57008046]
  [0.97392845 0.50355406 0.55398399]]

 [[0.41356769 0.41359919 0.89689954]
  [0.13622862 0.40647062 0.98915819]
  [0.62901997 0.65106184 0.09363538]]

 [[0.27910986 0.81785536 0.13489192]
  [0.32698794 0.31675061 0.74413763]
  [0.24833253 0.38412359 0.41165527]]]
[0.27286602 0.7565374  0.03819818 0.34440667 0.03709606 0.57008046
 0.97392845 0.50355406 0.55398399 0.41356769 0.41359919 0.89689954
 0.13622862 0.40647062 0.98915819 0.62901997 0.65106184 0.09363538
 0.27910986 0.81785536 0.13489192 0.32698794 0.31675061 0.74413763
 0.24833253 0.38412359 0.41165527]
11


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
X = np.random.random((10, 10))
Z = X.reshape(-1)
print(f"{np.amin(Z)=}, {np.amax(Z)=}")
# myanswer(13)
xMin, xMax = X.min(), X.max()
zMin, zMax = np.min(X), np.max(X)
print(f"{xMin=}, {xMax=}")
print(f"{zMin=}, {zMax=}")

np.amin(Z)=0.005721123308103815, np.amax(Z)=0.9955184372212649
xMin=0.005721123308103815, xMax=0.9955184372212649
zMin=0.005721123308103815, zMax=0.9955184372212649


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
X = np.random.random(30)
print(X)
meanX = np.mean(X)
m = X.mean()
print(f"{meanX=}, {m=}")
# myanswer(14)

[0.67590047 0.46347285 0.78991246 0.07042943 0.12687793 0.24970133
 0.78841758 0.16392238 0.2102644  0.0456982  0.99875426 0.8029511
 0.5403909  0.05670159 0.60122373 0.36372587 0.72789412 0.07994502
 0.49170656 0.19727698 0.79190876 0.61055147 0.37086507 0.06372408
 0.87008167 0.77809718 0.90916314 0.30665132 0.12337449 0.28557325]
meanX=0.4518385865496793, m=0.4518385865496793


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
X = np.zeros((5, 5))
# borderIdx = X.shape[-1] - 1
# print(X.shape, col)
X[0][:] = X[-1][:] = 1
X.T[0][:] = X.T[-1][:] = 1
print(X, "\n")

# myanswer(15)
Z = np.ones((6, 6))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
X = np.ones((5,5))
# X = np.pad(X, pad_width=1, mode='constant', constant_values=0)
X = np.pad(X, pad_width=1)
print(X, "\n")
# np.info(np.pad)

X = np.ones((5, 5))
X[:, [0, -1]] = 0
X[[0, -1], :] = 0
print(X)
# answer(16)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
# myanswer(17)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
X = np.zeros((5,5))
for i in range(1, X.shape[-1]):
    X[i][i-1] = i
print(X, "\n")

print(np.diag(1+np.arange(4), k=-1))
# print(1+np.arange(4))
# myanswer(18)
# np.info(np.diag)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]] 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
X = np.zeros((8, 8), dtype=int)
# print(X)
X[0::2, 1::2] = 1
X[1::2, 0::2] = 1
print(X)
# answer(19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [280]:
X = np.arange(6*7*8).reshape((6,7,8))
idx = np.unravel_index(99, (6,7,8))
print(f"{idx=}, {X[idx]=}")
# print(X)
# np.info(np.unravel_index)
# answer(20)

idx=(1, 5, 3), X[idx]=99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [290]:
X = np.array([0,1,1,0]).reshape((2,2))
print(np.tile(X, (4,4)))
# np.info(np.tile)
# myanswer(21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [17]:
# np.info(np.random)
# np.info(np.random.normal)
Z = np.random.normal(0.0, scale=1.0, size=(100,100))
print(f"{np.mean(Z)=}, {np.std(Z)=}")

# myanswer(22)
X = np.random.random((100,100))
print(f"{np.mean(X)=}, {np.std(X)=}")

print("normalize: X ~ N(0, 1)")
X = (X - np.mean(X)) / np.std(X)
print(f"{np.mean(X)=}, {np.std(X)=}")

np.mean(Z)=-0.003010549613600839, np.std(Z)=0.9998620552991129
np.mean(X)=0.4957371554225429, np.std(X)=0.2901329122920752
normalize: X ~ N(0, 1)
np.mean(X)=1.3429257705865894e-16, np.std(X)=1.0


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [37]:
color = np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte)])
# answer(23)
help(color)

Help on dtype[void] object:

class dtype[void](dtype)
 |  Method resolution order:
 |      dtype[void]
 |      dtype
 |      builtins.object
 |  
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from numpy._DTypeMeta
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from dtype:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __mul__(self, value, /)
 |      Return

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [49]:
X = np.ones((5,3))
Y = 2 * np.ones((3,2))
print(X, "\n")
print(Y, "\n")

Z = X @ Y
print(Z)
# answer(24)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[2. 2.]
 [2. 2.]
 [2. 2.]] 

[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [68]:
X = np.arange(20)
# np.random.shuffle(X)
print(X)
pred = X >= 3 
pred &= X <= 8
print(pred)
X[pred] *= -1
print(X)

# myanswer(25)
Z = np.arange(12)
Z[(3 <= Z) & (Z <= 8)] *= -1
print(Z)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False  True  True  True  True  True  True False False False
 False False False False False False False False]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [86]:
print([ i for i in range(5)])
print(sum(range(5), -1))
print(np.sum(range(5), -1))
print(np.sum(range(5), axis=-1, initial=-1))
# np.info(np.sum)

[0, 1, 2, 3, 4]
9
10
9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [108]:
Z = np.arange(5)
print(Z)
print(Z**Z)
print(2<<Z)
print(Z>>2)
print(2<<Z>>2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z)
print(Z==Z)
# print(Z)

[0 1 2 3 4]
[  1   1   4  27 256]
[ 2  4  8 16 32]
[0 0 0 0 1]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]
[False False False False False]
[ True  True  True  True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

# myanswer(28)

nan
0
[0.]

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


/var/folders/xr/d9cpp2t502x85b23mh1c2mhc0000gp/T/ipykernel_21846/4201827364.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/xr/d9cpp2t502x85b23mh1c2mhc0000gp/T/ipykernel_21846/4201827364.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [137]:
X = np.random.random(10)
print(X)
print(np.ceil(X))

Z = np.random.uniform(-10, +10, 10)
print(Z)
print(f"{np.mean(Z)=}, {np.std(Z)=}")
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

myanswer(29)
np.info(np.where)

[0.21034578 0.36818233 0.37272741 0.11149104 0.66616892 0.67358884
 0.7884261  0.29248349 0.15727739 0.85999263]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-6.28326127 -5.5793792  -4.20613054  1.78444993  8.7062875  -0.79784442
  8.48336644 -5.26521639 -3.74823226 -3.37096784]
np.mean(Z)=-1.0276928063588038, np.std(Z)=5.314713461702654
[-7. -6. -5.  2.  9. -1.  9. -6. -4. -4.]
[-7. -6. -5.  2.  9. -1.  9. -6. -4. -4.]

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
 where()

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are


#### 30. How to find common values between two arrays? (★☆☆)

In [146]:
X = np.array(range(0, 10))
Y = np.array(range(4,8))
print(X, Y)
print(np.intersect1d(X, Y))

# answer(30)
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[0 1 2 3 4 5 6 7 8 9] [4 5 6 7]
[4 5 6 7]
[0 1 5 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)